#!/bin/bash

HERE="$(dirname "$(readlink -f "${0}")")"

# Custom AppRun script for Inkscape
# by Simon Peter

# Allow AppRun or the AppImage to be symlinked to, e.g.,
# /usr/local/bin/inkview
# or to be called with ./Inkscape*.AppImage inkview

if [ ! -z $APPIMAGE ] ; then
  BINARY_NAME=$(basename "$ARGV0")
else
  BINARY_NAME=$(basename "$0")
fi
if [ ! -z "$1" ] && [ -e "$HERE/bin/$1" ] ; then
  MAIN="$HERE/bin/$1" ; shift
elif [ ! -z "$1" ] && [ -e "$HERE/usr/bin/$1" ] ; then
  MAIN="$HERE/usr/bin/$1" ; shift
elif [ -e "$HERE/bin/$BINARY_NAME" ] ; then
  MAIN="$HERE/bin/$BINARY_NAME"
elif [ -e "$HERE/usr/bin/$BINARY_NAME" ] ; then
  MAIN="$HERE/usr/bin/$BINARY_NAME"
else
  MAIN="$HERE/usr/bin/inkscape"
fi

# Run experimental AppDir that bundles everything
# in case ld-linux-x86-64.so.2 is bundled

if [ -e "$HERE/lib/x86_64-linux-gnu/ld-linux-x86-64.so.2" ] ; then
  echo "Run experimental bundle that bundles everything"
  export LIBRARY_PATH="$HERE/usr/lib":$LIBRARY_PATH
  export LIBRARY_PATH="$HERE/lib":$LIBRARY_PATH
  export LIBRARY_PATH="$HERE/usr/lib/x86_64-linux-gnu":$LIBRARY_PATH
  export LIBRARY_PATH="$HERE/lib/x86_64-linux-gnu":$LIBRARY_PATH
  export LIBRARY_PATH="$HERE/usr/lib/x86_64-linux-gnu/pulseaudio":$LIBRARY_PATH
  export LIBRARY_PATH="$HERE/usr/lib/x86_64-linux-gnu/alsa-lib":$LIBRARY_PATH
  exec lib/x86_64-linux-gnu/ld-linux-x86-64.so.2 --inhibit-cache --library-path "${LIBRARY_PATH}" "${MAIN}" "$@"
else
  exec "${MAIN}" "$@"
fi
