# -*- mode: ruby -*-
# SPDX-License-Identifier: Apache-2.0
# vi: set ft=ruby :

# Partly based on chocolatey-test-environment Vagrantfile
# https://github.com/chocolatey-community/chocolatey-test-environment/blob/master/Vagrantfile
# which is (C) Present RealDimensions Software, LLC and licensed Apache-2.0

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://vagrantcloud.com/search.
  config.vm.box = "gusztavvargadr/windows-11"

  # Disable automatic box update checking. If you disable this, then
  # boxes will only be checked for updates when the user runs
  # `vagrant box outdated`. This is not recommended.
  # config.vm.box_check_update = false

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine. In the example below,
  # accessing "localhost:8080" will access port 80 on the guest machine.
  # NOTE: This will enable public access to the opened port
  # config.vm.network "forwarded_port", guest: 80, host: 8080

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine and only allow access
  # via 127.0.0.1 to disable public access
  # config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"

  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  # config.vm.network "private_network", ip: "192.168.33.10"

  # Create a public network, which generally matched to bridged network.
  # Bridged networks make the machine appear as another physical device on
  # your network.
  # config.vm.network "public_network"

  # Share an additional folder to the guest VM. The first argument is
  # the path on the host to the actual folder. The second argument is
  # the path on the guest to mount the folder. And the optional third
  # argument is a set of non-required options.
  # config.vm.synced_folder "../data", "/vagrant_data"

  # Disable the default share of the current code directory. Doing this
  # provides improved isolation between the vagrant box and your host
  # by making sure your Vagrantfile isn't accessible to the vagrant box.
  # If you use this you may want to enable additional shared subfolders as
  # shown above.
  config.vm.synced_folder ".", "/vagrant", disabled: true, SharedFoldersEnableSymlinksCreate: false

  # Provider-specific configuration so you can fine-tune various
  # backing providers for Vagrant. These expose provider-specific options.
  # Example for VirtualBox:
  #
  # config.vm.provider "virtualbox" do |vb|
  #   # Display the VirtualBox GUI when booting the machine
  #   vb.gui = true
  #
  #   # Customize the amount of memory on the VM:
  #   vb.memory = "1024"
  # end
  
  # a long boot timeout is needed for slow host systems
  config.vm.boot_timeout = 1800
  # to avoid WinRM errors in the middle of booting, we ensure that (max_tries * retry_delay) > boot_timeout:
  config.winrm.max_tries = 900
  config.winrm.retry_delay = 2
  
    # http://docs.vagrantup.com/v2/providers/configuration.html
  # http://docs.vagrantup.com/v2/virtualbox/configuration.html
  # Configuration when using VirtualBox
  config.vm.provider :virtualbox do |v, override|
    # Show the GUI
    v.gui = true
    # 10GB RAM
    v.customize ["modifyvm", :id, "--memory", "10000"]
    # 2 CPUs (note: with more CPUs you may need even more RAM)
    v.customize ["modifyvm", :id, "--cpus", "2"]
    # Video RAM is 32 MB
    v.customize ["modifyvm", :id, "--vram", 32]
    # For better DNS resolution
    v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    # No audo
    v.customize ["modifyvm", :id, "--audio", "none"]

    v.customize ["modifyvm", :id, "--clipboard", "disabled"]
    v.customize ["modifyvm", :id, "--draganddrop", "disabled"]
    # Clipboard enabled
    # v.customize ["modifyvm", :id, "--clipboard", "bidirectional"]
    # v.customize ["modifyvm", :id, "--draganddrop", "hosttoguest"]
    # For performance
    v.customize ["modifyvm", :id, "--usb", "off"]
    # Huge performance gain here
    v.linked_clone = true if Vagrant::VERSION >= '1.8.0'
  end
  
  # Configuration when using Hyper-V
  # https://www.vagrantup.com/docs/hyperv/configuration.html
  # https://technet.microsoft.com/en-us/library/dn798297(v=ws.11).aspx
  config.vm.provider :hyperv do |v, override|
    # 4GB RAM
    v.memory = 10000
    v.maxmemory = nil
    # 2 CPUs
    v.cpus = 2
    # The time in seconds to wait for the virtual machine to report an IP address
    v.ip_address_timeout = 240
    # Use differencing disk instead of cloning whole VHD
    if Vagrant::VERSION >= '2.1.2'
      v.linked_clone = true
    else
      v.differencing_disk = true
    end
    v.vm_integration_services = {
      guest_service_interface: true,
      heartbeat: true,
      key_value_pair_exchange: true,
      shutdown: true,
      time_synchronization: true,
      vss: true
  }
  end

  #
  # View the documentation for the provider you are using for more
  # information on available options.

  # Enable provisioning with a shell script. Additional provisioners such as
  # Ansible, Chef, Docker, Puppet and Salt are also available. Please see the
  # documentation for more information about their specific syntax and use.
  # config.vm.provision "shell", inline: <<-SHELL
  #   apt-get update
  #   apt-get install -y apache2
  # SHELL

  # Enable auto login
  script_autologin = <<'SHELL'
    Set-ItemProperty -Path 'HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Winlogon' -Name 'AutoAdminLogon' -Value '1';
    Set-ItemProperty -Path 'HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Winlogon' -Name 'DefaultUserName' -Value 'Vagrant'; 
    Set-ItemProperty -Path 'HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Winlogon' -Name 'DefaultPassword' -Value 'vagrant';
    Set-ItemProperty -Path 'HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Winlogon' -Name 'AutoLogonCount' -Value '9999999999999';
SHELL
  config.vm.provision "shell", inline: script_autologin, powershell_elevated_interactive: true
  

  # Set keyboard layout and language (Example: German keyboard but English language in Windows = en-DE)
  # --> Adjust the following line to your need (replacing 'en-DE') and remove the comment sign '#'.
  # The keyboard layout will become active after the next reboot.
  # config.vm.provision "shell", inline: "Set-WinUserLanguageList -Force -LanguageList en-DE"
  
  
  # Copy Inkscape buildtools folder
  # WORKAROUND Vagrant bug: ensure the folder already exists (otherwise the content gets copied into the destionation folder at first run, and at second runs into the buildtools/ subfolder of the destination)
  config.vm.provision "shell", inline: "mkdir -force C:/inkscape-buildtools-tmp/"
  config.vm.provision "file", source: "..", destination: "C:/inkscape-buildtools-tmp"
  
  # Setup Inkscape development environment
  config.vm.provision "shell", inline: "& C:/inkscape-buildtools-tmp/buildtools/windows-installFullDevEnv-part2.ps1", powershell_elevated_interactive: true
end
